# Generated by Django 6.0.5 on 2026-05-08 05:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tuman/Shahar',
                'verbose_name_plural': 'Tuman/Shaharlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Soha',
                'verbose_name_plural': 'Sohalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Kasb/Lavozim',
                'verbose_name_plural': 'Kasblar/Lavozimlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Viloyat/Hudud',
                'verbose_name_plural': 'Viloyatlar/Hududlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': "Ko'nikma",
                'verbose_name_plural': "Ko'nikmalar",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': "O'quv muassasasi",
                'verbose_name_plural': "O'quv muassasalari",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('inn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_project_app.district')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_project_app.region')),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+?998\\d{9}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('job_seeker', 'Ish izlovchi'), ('employer', 'Ish beruvchi')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='main_project_app.organization')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'OTP kod',
                'verbose_name_plural': 'OTP kodlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'code', 'is_used'], name='main_projec_email_4f4654_idx'), models.Index(fields=['-created_at'], name='main_projec_created_c1b060_idx')],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='main_project_app.region'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10)),
                ('profession_detail', models.TextField(blank=True)),
                ('career_level', models.CharField(choices=[('beginner', 'Ish faoliyatini yangi boshlamoqda'), ('junior', "Ish tajribasi kam, o'rganishga tayyor"), ('middle', 'Amaliyot va nazariy bilimlarga ega'), ('fresh_graduate', 'Yangi bitiruvchi'), ('experienced', 'Tajribali mutaxassis')], max_length=20)),
                ('expected_salary', models.PositiveBigIntegerField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('permanent', 'Doimiy'), ('seasonal', 'Mavsumiy'), ('daily', 'Kunlik')], max_length=20)),
                ('work_mode', models.CharField(choices=[('office', 'Odatiy (ish joyida)'), ('shift', 'Smenali ish'), ('remote', 'Masofaviy'), ('hybrid', 'Gibrid'), ('freelance', 'Kasanachilik')], max_length=20)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_social_registry', models.BooleanField(default=False)),
                ('has_driving_license', models.BooleanField(default=False)),
                ('driving_license_categories', models.CharField(blank=True, max_length=50)),
                ('employment_status', models.CharField(choices=[('actively_looking', 'Faol ish qidiruvchiman'), ('open_to_offers', "Yangi imkoniyatlarni ko'rib chiqayapman"), ('not_looking', 'Hozircha ish qidirmayapman')], max_length=30)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_project_app.district')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='main_project_app.profession')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_project_app.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='resumes', to='main_project_app.skill')),
            ],
            options={
                'verbose_name': 'Rezyume',
                'verbose_name_plural': 'Rezyumelar',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issued_date', models.DateField()),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='main_project_app.resume')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='UniversityDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='main_project_app.university')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['name'],
                'unique_together': {('university', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_level', models.CharField(choices=[('secondary_special', "O'rta maxsus"), ('bachelor', 'Bakalavr'), ('master', 'Magistratura'), ('phd', 'PhD')], max_length=20)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_studying', models.BooleanField(default=False)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='main_project_app.resume')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educations', to='main_project_app.university')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_project_app.universitydirection')),
            ],
            options={
                'verbose_name': "Ta'lim",
                'verbose_name_plural': "Ta'limlar",
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('payment_type', models.CharField(choices=[('monthly', 'Oylik'), ('piecework', 'Ishbay'), ('hourly', 'Soatbay'), ('negotiable', 'Shartnomaviy')], max_length=20)),
                ('salary_from', models.PositiveBigIntegerField(blank=True, null=True)),
                ('salary_to', models.PositiveBigIntegerField(blank=True, null=True)),
                ('experience_required', models.CharField(choices=[('no_req', 'Talab etilmaydi'), ('lt_1', '1 yilgacha'), ('1_3', '1-3 yil'), ('3_5', '3-5 yil'), ('gt_5', '5 yildan ortiq')], max_length=20)),
                ('education_level', models.CharField(choices=[('any', 'Ahamiyatga ega emas'), ('secondary_special', "O'rta maxsus"), ('bachelor', 'Oliy (Bakalavr)'), ('master', 'Oliy (Magistratura)'), ('phd', 'PhD')], default='any', max_length=20)),
                ('employment_type', models.CharField(choices=[('permanent', 'Doimiy'), ('seasonal', 'Mavsumiy'), ('daily', 'Kunlik')], max_length=20)),
                ('work_mode', models.CharField(choices=[('office', 'Odatiy'), ('shift', 'Smenali'), ('remote', 'Masofaviy'), ('hybrid', 'Gibrid')], max_length=20)),
                ('work_schedule', models.CharField(blank=True, choices=[('6/1', '6/1'), ('5/2', '5/2'), ('4/4', '4/4'), ('4/3', '4/3'), ('4/2', '4/2'), ('3/3', '3/3'), ('3/2', '3/2'), ('2/2', '2/2'), ('2/1', '2/1'), ('1/3', '1/3'), ('1/2', '1/2'), ('free', 'Erkin grafik')], max_length=10)),
                ('gender', models.CharField(choices=[('any', 'Ahamiyatsiz'), ('male', 'Erkak'), ('female', 'Ayol')], default='any', max_length=10)),
                ('age_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('for_disabled', models.BooleanField(default=False)),
                ('for_graduates', models.BooleanField(default=False)),
                ('for_students', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_project_app.district')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_project_app.industry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='main_project_app.organization')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='main_project_app.profession')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_project_app.region')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('start_month', models.PositiveSmallIntegerField()),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('responsibilities', models.TextField(blank=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='main_project_app.resume')),
            ],
            options={
                'verbose_name': 'Ish tajribasi',
                'verbose_name_plural': 'Ish tajribalari',
                'ordering': ['-start_year', '-start_month'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'name')},
        ),
        migrations.CreateModel(
            name='ResumeLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', "O'zbek tili"), ('ru', 'Rus tili'), ('en', 'Ingliz tili'), ('tr', 'Turk tili'), ('ko', 'Koreys tili'), ('zh', 'Xitoy tili (Mandarin)'), ('de', 'Nemis tili'), ('ja', 'Yapon tili'), ('hi', 'Hind tili'), ('es', 'Ispan tili'), ('fr', 'Fransuz tili'), ('pt', 'Portugal tili'), ('ur', 'Urdu'), ('id', 'Indonez tili'), ('kaa', 'Qoraqalpoq tili'), ('tg', 'Tojik tili'), ('kk', 'Qozoq tili'), ('ky', "Qirg'iz tili"), ('ar', 'Arab tili')], max_length=10)),
                ('level', models.CharField(choices=[('A1', "A1 — Boshlang'ich"), ('A2', 'A2 — Elementar'), ('B1', "B1 — O'rta"), ('B2', "B2 — O'rtadan yuqori"), ('C1', "C1 — Ilg'or"), ('C2', 'C2 — Mukammal daraja')], max_length=5)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='main_project_app.resume')),
            ],
            options={
                'verbose_name': 'Rezyume tili',
                'verbose_name_plural': 'Rezyume tillari',
                'unique_together': {('resume', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ResumeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_views', to='main_project_app.resume')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Rezyume ko'rishi",
                'verbose_name_plural': "Rezyume ko'rishlari",
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['resume', '-viewed_at'], name='main_projec_resume__85d33a_idx'), models.Index(fields=['viewer', '-viewed_at'], name='main_projec_viewer__adf6c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('applied', 'Ariza (izlovchi → vakansiya)'), ('invited', 'Taklif (beruvchi → rezyume)')], default='applied', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('viewed', "Ko'rildi"), ('invited', 'Taklif yuborildi'), ('interview', 'Suhbatga chaqirildi'), ('accepted', 'Qabul qilindi'), ('hired', 'Ishga qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=20)),
                ('cover_letter', models.TextField(blank=True)),
                ('note', models.TextField(blank=True, help_text='Ish beruvchi izohi')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main_project_app.resume')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main_project_app.vacancy')),
            ],
            options={
                'verbose_name': 'Ariza/Taklif',
                'verbose_name_plural': 'Arizalar/Takliflar',
                'ordering': ['-applied_at'],
                'unique_together': {('vacancy', 'resume', 'direction')},
            },
        ),
        migrations.CreateModel(
            name='VacancyLanguageRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', "O'zbek tili"), ('ru', 'Rus tili'), ('en', 'Ingliz tili'), ('tr', 'Turk tili'), ('ko', 'Koreys tili'), ('zh', 'Xitoy tili (Mandarin)'), ('de', 'Nemis tili')], max_length=10)),
                ('min_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=5)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_requirements', to='main_project_app.vacancy')),
            ],
            options={
                'verbose_name': 'Vakansiya til talabi',
                'verbose_name_plural': 'Vakansiya til talablari',
                'unique_together': {('vacancy', 'language')},
            },
        ),
        migrations.CreateModel(
            name='VacancyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_vacancies', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main_project_app.vacancy')),
            ],
            options={
                'verbose_name': 'Saqlangan vakansiya',
                'verbose_name_plural': 'Saqlangan vakansiyalar',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'vacancy')},
            },
        ),
    ]
