# Generated by Django 6.0.5 on 2026-05-08 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('application_received', 'Yangi ariza qabul qilindi'), ('application_status_changed', "Ariza holati o'zgardi"), ('invitation_received', 'Sizga taklif keldi'), ('invitation_accepted', 'Taklif qabul qilindi'), ('vacancy_liked', 'Vakansiya saqlandi'), ('system', 'Tizim xabari')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('registration', "Ro'yxatdan o'tish"), ('password_reset', 'Parolni tiklash')], default='registration', max_length=20),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['email', 'purpose', 'is_used'], name='main_projec_email_ed2608_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='main_project_app.application'),
        ),
        migrations.AddField(
            model_name='notification',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='main_project_app.resume'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='Bildirishnoma yuboriladigan foydalanuvchi', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='main_project_app.vacancy'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='main_projec_user_id_eb15f1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='main_projec_user_id_cc9c05_idx'),
        ),
    ]
