# Generated by Django 6.0.5 on 2026-05-08 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_project_app', '0002_notification_otpcode_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('job_seeker', 'Ish izlovchi'), ('employer', 'Ish beruvchi'), ('admin', 'Administrator')], max_length=20),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('vacancy', 'Vakansiya'), ('resume', 'Rezyume'), ('organization', 'Tashkilot'), ('user', 'Foydalanuvchi')], max_length=20)),
                ('target_id', models.PositiveBigIntegerField(help_text="Shikoyat qilinayotgan ob'ekt ID si")),
                ('reason', models.CharField(choices=[('spam', 'Spam yoki reklama'), ('fraud', 'Aldash, firibgarlik'), ('inappropriate', 'Nomaqbul kontent'), ('fake', "Soxta ma'lumot"), ('discrimination', 'Kamsitish'), ('other', 'Boshqa sabab')], max_length=20)),
                ('description', models.TextField(blank=True, help_text="Qo'shimcha tushuntirish")),
                ('status', models.CharField(choices=[('pending', "Ko'rib chiqilmoqda"), ('resolved', 'Hal qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=20)),
                ('resolution_note', models.TextField(blank=True, help_text='Admin javobi/qarori')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(help_text='Shikoyat yuborgan foydalanuvchi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shikoyat',
                'verbose_name_plural': 'Shikoyatlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='main_projec_status_74b1ba_idx'), models.Index(fields=['target_type', 'target_id'], name='main_projec_target__ad3551_idx')],
            },
        ),
    ]
