# Generated by Django 6.0.5 on 2026-05-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_project_app', '0003_alter_user_role_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profil rasmi (kvadrat shaklida tavsiya etiladi)', null=True, upload_to='user_avatars/'),
        ),
    ]
